### PR TITLE
Update file according to glitch

### PR DESCRIPTION
**Pull request by wchiquito**
Update file according to glitch

### CODE REVIEW

**Comment by blackmad** [comment]
Hi, thanks for the PR - I'm not sure what you mean by "update according to glitch" - we'd like these files to stay formatted in the notion style. What did you do that reformatted them like this and why is it helpful?

**Comment by wchiquito** [comment]
In your [documentation page](https://developers.notion.com/), specifically in the [Example code](https://developers.notion.com/page/examples) section you have two links for **Send an email from a Notion trigger**: [Fork repository on GitHub](https://github.com/makenotion/notion-sdk-js/tree/main/examples/database-update-send-email) and [View live example](https://glitch.com/edit/#!/notion-database-email-update?path=README.md%3A11%3A33) ([glitch.com](https://glitch.com/)) but the code for both is different.

**Comment by blackmad** [comment]
Ah, got it - we'll update the code on glitch to look like what's in the repo, I had thought it would sync to github!

**Comment by wchiquito** [comment]
Will the sync be Glitch -> GitHub or GitHub -> Glitch?

**Comment by lao9** [comment]
Hey @wchiquito - I cleaned up both the glitch and client libraries examples to be consistent in https://github.com/makenotion/notion-sdk-js/pull/143 and https://github.com/makenotion/notion-sdk-js/pull/144. Thanks for raising! Closing this now.

**Pull request closed without merging**
