### PR TITLE
chore(Client): typed `notionVersion`

### PR DESCRIPTION
**Pull request by 2nthony**

### CODE REVIEW

**Comment by justjake** [comment]
@2nthony `"some string literal" | string` in Typescript will reduce to just `string`, so I don't see a reason to make this change.

**Comment by 2nthony** [comment]
yeah, I think `notionVersion: 'versionString' | 'versionString' | ...` is more reasonable.

**Comment by 2nthony** [comment]
in my case is, i have to find out the correct version number on api doc.

so i wondering, why not with type intellisense.

**Comment by justjake** [comment]
I don't think this offers any intellisense improvement, though, because the type is reduced to just `string`. VS Code and the Typescript playground don't offer any completions for me.

image


[Playground link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAypDGBLAZo+A1CAnAzog9gHZQC8UA5AEwAMNAtNQIwOPlQA+FNllLL5AKFCQoAcQiFsAQwA2mXAWJk4EJKgzY8RDlBzAsiQgHMBA+ET26EKNAC5Y19fK1KoAIm7U+TN1AD0flAAKlIARlDmALZgMhDAiroArkZGEHo4UABumoo4ZhbAUKmSWLL24iWyzglkbr4BwWER+NGx8doAFlIZhPhJKWnthDhAA)

**Pull request closed without merging**
