### PR TITLE
Apply prettier

### PR DESCRIPTION
**Pull request by justjake**
Add prettier and apply to the codebase. This should keep the codebase looking nice.

### CODE REVIEW

**Comment by blackmad** [comment]
why "don't use tabs" when our internal repo does?

**Comment by blackmad** [comment]
other thing to clean up is that "//comments are formatted without a space after the double slash"

**Comment by justjake** [comment]
@blackmad i think tabs inside markdown doc examples is pretty iffy, it indents things a lot and makes them hard to read. In a code editor it’s easy to configure tabspaces=2, not sure how GitHub or other markdown renders handle the legibility issues

**Comment by justjake** [comment]
For me the primary issue is just having a .prettierrc here so when I save source code files in my editor, I don’t produce a big diff

**Review by blackmad — APPROVED** [review]

**Pull request merged**
