### PR TITLE
fix: update examples to use named methods

### LINKED ISSUE #14: Migrate examples to used named methods
Depends on #5, #13 

Currently, the examples are using the `request()` method to make requests. These calls should be replaced with calls to named methods on the client, such as `pages.create()`.

### PR DESCRIPTION
**Pull request by chazkiker2**
# Description

- [x] closes #14 
- [x] Update each example to use named methods rather than `notion.request`
  - [x] `examples/github-issue-sync`
  - [x] `examples/database-update-send-email`
  - [x] `examples/generate-random-data` **(already implemented named methods)**

### CODE REVIEW

**Comment by chazkiker2** [comment]
Ready to be reviewed & merged 😄

**Comment by chazkiker2** [comment]
@pllnk @97agupta review?

**Comment by lao9** [comment]
Hi @chazkiker2 - I updated two of the examples last Friday to follow better style guides / match the glitch examples. Mind updating your branch with the latest changes and re-request a review?

**Comment by chazkiker2** [comment]
@lao9 I merged your changes in! Should be good to go now.

would you be willing to review, now?

**Comment by chazkiker2** [comment]
@lao9 this is not an overly complicated PR and I'm a bit shocked it's been sitting here for a month with no action. 

Feel free to take it or leave it; and if you have changes to request with a review, I'll gladly make said changes. 

But fair warning: I will not re-update these changes again a month from now if a separate PR is merged with changes to incorporate.

**Comment by lao9** [comment]
@chazkiker2 - I missed your tag from last week and will make sure this gets merged today. We appreciate your patience!

**Comment by lao9** [comment]
@chazkiker2 - There were still some issues running your suggestions through our linter, but upon taking a deeper look at these examples in glitch, and I feel that they actually needed more TLC overall. 

I took some of your suggestions / changes from this PR and cleaned it up to be more aligned with Notion's own internal code quality and style, so I'm going to close this PR in favor of https://github.com/makenotion/notion-sdk-js/pull/158

Thank you for your help! 🙏

**Comment by chazkiker2** [comment]
@lao9 no worries at all, thanks for taking over to notion-ify it and get it in a place you're happy with 😄

cheers 🥳

**Pull request closed without merging**
